app:
  name: provisioning-downloader
  namespace: cmp-stage-provisioning
deployment:
  name: provisioning-downloader
container:
  name: provisioning-downloader-container
  image: harbor.kore.korewireless.com/kore-provisioning/provisioning-downloader
  tag: latest
service:
  name: provisioning-downloader
  port: 9000
ingress:
  name: provisioning-downloader
  host: provisioning-downloader.staging.k1d.k8.cin.kore.korewireless.com
  env: staging
kafka:
  endpoint: provisioning-broker-service
  port: 9092
postgres:
  name: default
  database: provisioning-stage-db
  schema: public
  namespace: cmp-stage-provisioning
  dbusername: pgouser
  username: pgouser
  contact:
    point: provisioning-stage-db
    port: 5432
variables:
  workingEnv: staging
  kafkaK8Broker: "kafka.cpro.dev.nginx.k1d.k8.cin.kore.korewireless.com:9094"
  kafkaGroupId: "connectivity-provisioning-downloader-group"
  connectInternalToK8Kafka: false
  dbRetryInterval: 1
  brokersAvailabilityCheckInterval: 1
  downloadRequestTopic: "connectivity.staging.provisioning.download.requests"
  reportsTopic: "connectivity.stage.provisioning.reports"
  ProvisioningCEPHAccessKey: 'G0PZP12B32MUBDL3WJV9'
  ProvisioningCEPHSecretKey: '4q8WIeLjk0idHz6hCOnw6ODThazvTsz3WZ62rvKt'
  ProvisioningCEPHBucketName: 'cmp-provisioning'
  ProvisioningCEPHPath: 'stage_cmp_provisioning'
  ProvisioningCEPHPort: 443
  ProvisioningCEPHServer: 's3.ceph.cin.kore.korewireless.com'
  ProvisioningCEPHSSL: 'true'
  kafkaInternalProvisoningApiTopic: 'connectivity.staging.provisioning.pendingEnrichment.requests'
  notificationKafkaTopic: 'connectivity.stage.provisioning.notifications'
  kafkaK8prefix : ''
  GDSUrl: 'https://globaldeviceservice.stage.k1d.k8.cin.kore.korewireless.com/api/v1'
  GCSUrl: 'https://globalcustomerservice.stage.k1d.k8.cin.kore.korewireless.com/api/v1'
  ParsecUrl: 'https://parsec.stage.k1d.k8.cin.kore.korewireless.com'
  elasticClusterUrl: 'https://connectproelasticingress-dev.ngxin.k1d.k8.cin.kore.korewireless.com:443/'
  ProvisioningK8ElasticUser: 'elastic'
  elasticProvisioningRequestIndex: 'stage-provisioning_requests-search'
  redisUserName: 'provisioning'
  redisPort: 6379
  redisHost: 'cpro-redis-cluster-dev-leader-headless.cpro-redis-cluster-dev'
  redisCacheKeyPrefix: 'provisioning:staging:'
  isRedisCachingEnabledForOrganizationDetails: 'true'
  requestDetailsFromProvisioningEnabled: 'true'